version: '3.1'

services:

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
 
  frontend:
    build: frontend/.
    restart: on-failure
    volumes:
      - bundles_volume:/opt/starburger/app/bundles

  web:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: unless-stopped
    volumes:
      - static_volume:/opt/starburger/app/staticfiles
      - media_volume:/opt/starburger/app/media
      - bundles_volume:/opt/starburger/app/bundles
    ports:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - frontend
    command: gunicorn star_burger.wsgi:application --bind 127.0.0.1:8000 --workers 3

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
     - ./nginx:/etc/nginx/templates
     - static_volume:/opt/starburger/app/staticfiles
     - media_volume:/opt/starburger/app/media
    ports:
     - "8888:80"
    environment:
     - NGINX_PORT=80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  bundles_volume:
