# Generated by Django 3.2.15 on 2023-07-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20230710_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('COLLECT', 'В сборке'), ('IN_DELIVERY', 'У курьера'), ('COMPLETED', 'Завершен')], db_index=True, default='NEW', max_length=11, verbose_name='статус'),
        ),
    ]
