# Generated by Django 3.2.15 on 2023-07-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230711_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='executing_restaurant',
        ),
    ]
