# Generated by Django 3.2.15 on 2023-07-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_rename_restaurant_order_executing_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('NOT_SPECIFIED', 'Не указано'), ('IMMEDIATE', 'Сразу'), ('BANK_CARD', 'Картой'), ('CASH', 'Наличными')], db_index=True, default='NOT_SPECIFIED', max_length=13, verbose_name='Способ оплаты'),
        ),
    ]
