# Generated by Django 3.2.15 on 2023-07-10 09:14

from django.db import migrations


def fill_orderproduct_price(apps, schema_editor):
    OrderElement = apps.get_model("foodcartapp", "OrderElement")
    for order_product in OrderElement.objects.all().iterator():
        order_product.price = order_product.product.price
        order_product.save()


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0039_auto_20230710_1211'),
    ]

    operations = [
        migrations.RunPython(fill_orderproduct_price),
    ]
